const tempmovie=[
    {

      id:19,
      name:"Theri",
      director:"Atlee",
      src:"theri.png"
    },
    {
      id:"10",
      name:"Mersal",
      director:"Atlee",
      src:"mersal.png"


    },
    {
      id:"16",
      name:"Bigil",
      director:"Atlee",
      src:"bigil.png"
    },
    {
      id:"17",
      name:"Master",
      director:"Loki",
      src:"master.png"
    },
    {
      id:"15",
      name:"Leo",
      director:"Loki",
      src:"leo.png"
    },
    {
      id:"12",
      name:"Doctor",
      director:"Nelson",
      src:"doctor.png"
    },
    {
      id:"13",
      name:"Jailer",
      director:"Nelson",
      src:"jailer.png"
    },
    {
      id:"24",
      name:"Beast",
      director:"Nelson",
      src:"beast.png"
    },
    {
      id:"35",
      name:"Vikram",
      director:"Loki",
      src:"vikram.png"
    },
    {
      id:"47",
      name:"Nanban",
      director:"Shankar",
      src:"nanban.png"
    },
    {
      id:"46",
      name:"Enthiran",
      director:"Shankar",
      src:"enthiran.png"
    },

    
  ]
